//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeribisTasarım {
    
    
    public partial class Fırsat {
        
        /// <summary>
        /// ButtonFirsatEkleYeni control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ButtonFirsatEkleYeni;
        
        /// <summary>
        /// ButtonFirsatEkleKaydet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ButtonFirsatEkleKaydet;
        
        /// <summary>
        /// ButtonFirsatEkleSil control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ButtonFirsatEkleSil;
        
        /// <summary>
        /// FIRSAT_KODU control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList FIRSAT_KODU;
        
        /// <summary>
        /// FIRSAT_FIRMA_ADI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList FIRSAT_FIRMA_ADI;
        
        /// <summary>
        /// FIRSAT_KONTAK control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList FIRSAT_KONTAK;
        
        /// <summary>
        /// FIRSAT_EVRAK_TIPI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList FIRSAT_EVRAK_TIPI;
        
        /// <summary>
        /// FIRSAT_EVRAK_NO1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox FIRSAT_EVRAK_NO1;
        
        /// <summary>
        /// FIRSAT_EVRAK_NO2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox FIRSAT_EVRAK_NO2;
        
        /// <summary>
        /// FIRSAT_CINSI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList FIRSAT_CINSI;
        
        /// <summary>
        /// FIRSAT_EVRAK_TARIHI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox FIRSAT_EVRAK_TARIHI;
        
        /// <summary>
        /// FIRSAT_TEMSILCISI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList FIRSAT_TEMSILCISI;
        
        /// <summary>
        /// FIRSAT_STOK_BAGIMSIZ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBoxList FIRSAT_STOK_BAGIMSIZ;
        
        /// <summary>
        /// FIRSAT_REVIZYON control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList FIRSAT_REVIZYON;
        
        /// <summary>
        /// FIRSAT_TESLIM_SEKLI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList FIRSAT_TESLIM_SEKLI;
        
        /// <summary>
        /// FIRSAT_ODEME_SEKLI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList FIRSAT_ODEME_SEKLI;
        
        /// <summary>
        /// FIRSAT_TAKIP_YON control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList FIRSAT_TAKIP_YON;
        
        /// <summary>
        /// FIRSAT_TAKIP_ASAMASI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList FIRSAT_TAKIP_ASAMASI;
        
        /// <summary>
        /// FIRSAT_GECERLILIK_TARIHI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox FIRSAT_GECERLILIK_TARIHI;
        
        /// <summary>
        /// FIRSAT_PROJE control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList FIRSAT_PROJE;
        
        /// <summary>
        /// FIRSAT_SON_DURUM control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList FIRSAT_SON_DURUM;
        
        /// <summary>
        /// FIRSAT_NEDEN_KAYBETTIK control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList FIRSAT_NEDEN_KAYBETTIK;
        
        /// <summary>
        /// FIRSAT_KAZANAN_RAKIP_FIRMA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList FIRSAT_KAZANAN_RAKIP_FIRMA;
        
        /// <summary>
        /// FIRSAT_ACIKLAMA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox FIRSAT_ACIKLAMA;
    }
}
